services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: store_admin


  weather_app:
    build: .
    container_name: weather_app
    entrypoint: [ "sh", "-c" ]
    command: >
      "python manage.py makemigrations --noinput &&
       python manage.py migrate --noinput &&
       python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: weather_db
      DATABASE_USER: store_admin
      DATABASE_PASSWORD: store_admin
      DATABASE_HOST: db
      DATABASE_PORT: 5432

volumes:
  postgres_data:
