version: "3.8"

services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: store_admin
      POSTGRES_PASSWORD: store_admin


  weather_app:
    build: .
    container_name: weather_app
    ports:
      - "8000:8000"
    depends_on:
      - db
